name: 'Alert Manager'
description: 'Create an issue when a new alert is created'
inputs:
  token:
    description: 'Token to use for authentication'
    required: true
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.20.4'

    - run: GITHUB_TOKEN=${{ inputs.who-to-greet }} go run ${{ github.action_path }}/main.go
      shell: bash
branding:
  icon: 'lock'
  color: 'yellow'