name: 'Alert Manager'
description: 'Create an issue when a new alert is created'
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.20.4'

    - run: go run ${{ github.action_path }}/main.go
      shell: bash
branding:
  icon: 'lock'
  color: 'yellow'